name: Build binaries (Release)
on:
  push:
    tags:
      - "v*.*.*"

jobs:
    build:
        container:
            image: fedora:latest
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: dnf install -y gcc gcc-c++ make pkg-config musl-devel musl-libc-static musl-clang
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                target: x86_64-unknown-linux-musl

            - uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Build release binaries
              run: |
                  rustup target add x86_64-unknown-linux-musl
                  make package CARGO_ARGS="--target=x86_64-unknown-linux-musl" CARGO_TARGET="x86_64-unknown-linux-musl/release"
            
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: boson-x86_64-unknown-linux-musl
                path: boson.tar.zst

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                files: boson.tar.zst
              